name: Push Docker Image to Docker Hub
on:
  push:
    branches:
      - 'main'
    tags:
      - '**'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ktemple77/nodejs-ci
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} # Docker Hub에 사용할 사용자 ID (Secret)
          password: ${{ secrets.DOCKER_HUB_PASSWORD }} # Docker Hub에 사용할 비밀번호 (Secret)

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }} # 빌드 후 생성된 태그
          labels: ${{ steps.docker_meta.outputs.labels }} # Docker 이미지 레이블
